[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

[[redirects]]
  from = "/robots.txt"
  to = "/robots.txt"
  status = 200
# Force redirect Netlify subdomain → .com
# ✅ Force all Netlify subdomain traffic to .com
[[redirects]]
  from = "https://proimagetotext.netlify.app/*"
  to = "https://proimagetotext.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
